### ISSUE TITLE
smokey the bear

### ISSUE THREAD

**Issue by HausemasterIssue** [Smokeybear12/dav1dclientassets#1]
did you know that the smokey the bear campaign made a whole generation afraid of and preventful of wildfires? wildfires are a key part of many ecosystems. naturally, they are usually started by a lightning bolt hitting one of the trees. however, when people always try to put out wildfires they end up caused even more of them. you see, when a fire burns a forest, it burns all the trees, old lumber, or dead twigs and logs, and causes them to die or burn. this leaves plenty of room for more plants to start growing after the fires. animals may also die, but more species will take their place. plus the soil get's a break from all the trees sucking up all the soil. in fact, the native americans did this routinely in controlled fires to help the forest. however, once european settlers started taking the land from the native americans, they prohibited them from doing this activity. so there would barely be any forest fires. this caused the ecosystem to be less biodeverse and old, dying trees would use up a lot of nutrients that could go to another generation of trees. nowdays, when a wildfire starts they are usually quickly and harshly put out, this is to minimize damage to the homes and ecosystem. however, damage to the ecosystem is actually good for it. i'm not saying you should go out and start burning trees, what i am saying is to stop people from causing forest fires, and instead get trained professionals to make controlled burns around old areas of the forest to make way for new plants and animals to grow and live there. that's what is happening right not in californa. there are some firefighters with limited support and funds from the californa government, but they are doing something that shouldn've been done a long time ago. they are setting up controlled burns around the forest to help burn the trees in a controlled, good way. now, you may be thinking, what if the fire get's out of hand? well, the people who do these controlled burns are very trained, and know how to quickly put them out if they spread too fast or cause unwanted damage to the forest. we should continue doing this, and these firefighters should get more support, because with climate change making things hotter, it's only going to get worse for these forests, now unless we do controlled burns, entire forests and homes could burn, so please, give them your support. smokey the bear was wrong, it was right in getting people to not set fires to forests, but it was wrong in saying the all forest fires are bad, in fact controlled ones can be very good. it's up to us to learn from the mistakes of the old generation, so we, can become better and make the earth a better place.

an informal essay by yours truly,

hause

**Comment by Smokeybear12** [comment]
Thanks for the interesting opinion; I enjoyed reading it. I must say that some of the details are inacurate. One of the greater points of the Smokey Bear campaign is to prevent forest fires. You are correct that forest fires are great for soil. It "cleans" the forest. However that can only be good in a controlled burn. Accidental fires can easily get out of hand, and you cannot possibly say an out of hand fire is good unless you are a mass murderer. This campaign is raising awareness for accidental fires, and protecting the community. Like I stated before, controlled fires are good. See here: https://smokeybear.com/en/about-wildland-fire/benefits-of-fire/prescribed-fires 

Smokey does not support people who conduct an accidental burn; accidentally. 

Smokey does support a carefully conducted fire that is beneficial to the enviornment around.

Make sure to do more research before you send out an opinion!

( even though you probably skidded it lmao )

Regards,

Andrew

**Comment by Smokeybear12** [comment]
Quite a lot was correct, however you failed to see the importance of Smokey in regards to awareness. Both are right, but the true answer is both.

**Comment by Smokeybear12** [comment]
Also accept the pr in the trolls repo



:]

**Comment by HausemasterIssue** [comment]
done

**Comment by Smokeybear12** [comment]
nice

**Comment by master7720** [comment]
bruh
